"""
Export engine — save TestResult objects to JSON, CSV, or HTML.
"""

from __future__ import annotations

import csv
import html as html_mod
import json
import os
from datetime import datetime
from typing import List

from ntt.core.utils import TestResult, Status, console


def _results_dir() -> str:
    """Return (and create) the default export directory."""
    d = os.path.join(os.getcwd(), "ntt_reports")
    os.makedirs(d, exist_ok=True)
    return d


def _auto_filename(ext: str) -> str:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    return os.path.join(_results_dir(), f"ntt_report_{ts}.{ext}")


def _result_to_dict(r: TestResult) -> dict:
    return {
        "title": r.title,
        "status": r.status.value,
        "target": r.target,
        "summary": r.summary,
        "details": r.details,
        "raw_output": r.raw_output,
        "timestamp": r.timestamp,
    }


# ── JSON ──────────────────────────────────────────────────────────────────────


def export_json(results: List[TestResult], path: str = "") -> str:
    """Export results to a JSON file.  Returns the written path."""
    path = path or _auto_filename("json")
    data = [_result_to_dict(r) for r in results]
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
    return path


# ── CSV ───────────────────────────────────────────────────────────────────────


def export_csv(results: List[TestResult], path: str = "") -> str:
    """Export results to a CSV file.  Returns the written path."""
    path = path or _auto_filename("csv")
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["Timestamp", "Title", "Status", "Target", "Summary", "Details"])
        for r in results:
            writer.writerow([
                r.timestamp,
                r.title,
                r.status.value,
                r.target,
                r.summary,
                " | ".join(r.details),
            ])
    return path


# ── HTML ──────────────────────────────────────────────────────────────────────


_HTML_HEADER = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>NTT Report</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 2em; background: #f4f4f4; color: #222; }
  h1 { color: #0064a5; }
  table { border-collapse: collapse; width: 100%%; margin-top: 1em; }
  th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; vertical-align: top; }
  th { background: #0064a5; color: #fff; }
  tr:nth-child(even) { background: #eaf2f8; }
  .pass { color: green; font-weight: bold; }
  .fail { color: red; font-weight: bold; }
  .warn { color: orange; font-weight: bold; }
  .err  { color: red; font-weight: bold; }
  .details { font-size: 0.85em; white-space: pre-wrap; }
  footer { margin-top: 2em; color: #888; font-size: 0.8em; }
</style>
</head>
<body>
<h1>NTT &mdash; Network Troubleshooting Report</h1>
<p>Generated: %(timestamp)s</p>
<table>
<tr><th>#</th><th>Timestamp</th><th>Test</th><th>Status</th><th>Target</th><th>Summary</th><th>Details</th></tr>
"""

_HTML_FOOTER = """\
</table>
<footer>Report generated by Network Troubleshooting Toolkit (NTT)</footer>
</body>
</html>
"""

_STATUS_CSS = {
    Status.SUCCESS: "pass",
    Status.FAILURE: "fail",
    Status.PARTIAL: "warn",
    Status.ERROR: "err",
}


def export_html(results: List[TestResult], path: str = "") -> str:
    """Export results to an HTML report.  Returns the written path."""
    path = path or _auto_filename("html")
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    rows: list[str] = []
    for i, r in enumerate(results, 1):
        css = _STATUS_CSS.get(r.status, "")
        details_html = html_mod.escape("\n".join(r.details))
        rows.append(
            f"<tr>"
            f"<td>{i}</td>"
            f"<td>{html_mod.escape(r.timestamp)}</td>"
            f"<td>{html_mod.escape(r.title)}</td>"
            f"<td class='{css}'>{html_mod.escape(r.status.value.upper())}</td>"
            f"<td>{html_mod.escape(r.target)}</td>"
            f"<td>{html_mod.escape(r.summary)}</td>"
            f"<td class='details'>{details_html}</td>"
            f"</tr>\n"
        )

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_HTML_HEADER % {"timestamp": now})
        fh.writelines(rows)
        fh.write(_HTML_FOOTER)
    return path


# ── Convenience ───────────────────────────────────────────────────────────────


def export_results(results: List[TestResult], fmt: str = "json", path: str = "") -> str:
    """High-level dispatcher.  *fmt* must be ``json``, ``csv``, or ``html``."""
    fmt = fmt.lower().strip()
    if fmt == "json":
        return export_json(results, path)
    elif fmt == "csv":
        return export_csv(results, path)
    elif fmt == "html":
        return export_html(results, path)
    else:
        raise ValueError(f"Unsupported export format: '{fmt}'. Use json, csv, or html.")
